### ISSUE TITLE
When using this browser on Quest2 to play streaming media, there may be noise interference.

### ISSUE THREAD

**Issue by GD2021** [Igalia/wolvic-chromium#116]
A sound similar to electrical buzzing
I tried sideloading several browsers and found that those based on the Chrome engine experienced this issue, while those powered by the Firefox engine worked fine. However, Meta Browser is an exception; it operates normally.

**Comment by svillar** [comment]
Which device?

**Comment by GD2021** [comment]
Quest2

**Comment by svillar** [comment]
We haven't observed this, and it's quite hard to verify since it doesn't appear to be something easy to spot. Please do reopen this if you find an easy way to reproduce/verify this.
