### ISSUE TITLE
wrong controllers shown in immersive mode on HTC Vive XR Elite

### ISSUE THREAD

**Issue by matthargett** [Igalia/wolvic-chromium#120]
When starting up and in the browser app (AC 121.1.0) environment, before entering immersive mode in browser, correct controller models are shown (even though their sticks and buttons aren't animated).

After entering immersive mode, it shows the incorrect controllers and doesn't correctly map the squeeze button on the XRE controllers.
![Screenshot 2024-10-07 at 11 18 19 PM](https://github.com/user-attachments/assets/a0539358-1a3e-4f59-81dc-b0996a58c146)

Note that even on the brand new Pico 4 Ultra, our WebXR app shows the correct controllers because this is a browser-level issue.

**Comment by svillar** [comment]
Showing the incorrect controllers is expected. The controllers shown in WebXR are not rendered by the browser but by the web engine itself. The engine downloads them from the WebXR input profiles registry. As you can see [here](https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/registry/profiles/htc) there are no controller profiles available for the XR Elite so I guess HTC fallbacks to using a similar one.

You might want to ask them to upload a valid model for the Elite device, but as far as I can see the latest update from HTC in that repo is from 3 years ago
