### ISSUE TITLE
BabylonJS WebXR Hands demos error instead of going into immersive mode on Vive XR Elite

### ISSUE THREAD

**Issue by matthargett** [Igalia/wolvic-chromium#128]
The BabylonJS Hands demo apps do not successfully go into immersive mode in the Vive XR Elite browser AC 121.1.0.

![Screenshot 2024-10-08 at 12 18 51 AM](https://github.com/user-attachments/assets/0217cd84-9216-4445-924c-10f43f0181b4)

**Comment by svillar** [comment]
Working fine in Chromium 1.0 release in Meta. If it does not work on HTC I guess you'd have to report that downstream.

See video:
https://github.com/user-attachments/assets/5faa16ec-1d43-485a-8502-c4e8df9e221f

**Comment by svillar** [comment]
Thanks for the report anyway!!!
